# Generated by Django 5.1.3 on 2025-01-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='bankLoging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=120)),
                ('mobile_no', models.BigIntegerField()),
                ('password', models.CharField(max_length=120)),
                ('credited_detials', models.CharField(max_length=500, null=True)),
                ('deposit_detials', models.CharField(max_length=500, null=True)),
                ('bank_balance', models.BigIntegerField(default=0, null=True)),
            ],
        ),
    ]
