# Generated by Django 5.1.4 on 2025-01-05 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankloging',
            name='credited_detials',
        ),
        migrations.RemoveField(
            model_name='bankloging',
            name='deposit_detials',
        ),
        migrations.CreateModel(
            name='transaction_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credited_detials', models.CharField(max_length=500)),
                ('deposit_detials', models.CharField(max_length=500)),
                ('account_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='Bankapp.bankloging')),
            ],
        ),
    ]
