# Generated by Django 5.1.4 on 2025-01-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0002_remove_bankloging_credited_detials_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_details',
            old_name='account_no',
            new_name='my_account',
        ),
        migrations.AddField(
            model_name='transaction_details',
            name='account_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
