# Generated by Django 5.1.4 on 2025-01-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0003_rename_account_no_transaction_details_my_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applogin',
            name='email',
            field=models.EmailField(max_length=120),
        ),
        migrations.AlterField(
            model_name='applogin',
            name='password',
            field=models.CharField(max_length=120),
        ),
    ]
