# Generated by Django 5.1.4 on 2025-01-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0005_rename_account_number_transaction_details_account_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_details',
            old_name='my_account_id',
            new_name='my_account',
        ),
    ]
