# Generated by Django 5.1.4 on 2025-01-06 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0006_rename_my_account_id_transaction_details_my_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_details',
            name='my_account',
        ),
        migrations.AlterField(
            model_name='transaction_details',
            name='account_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bankapp.bankloging'),
            preserve_default=False,
        ),
    ]
