# Generated by Django 5.1.4 on 2025-01-06 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0008_alter_transaction_details_credited_detials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_details',
            name='account_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bankapp.bankloging'),
        ),
    ]
