# Generated by Django 5.1.4 on 2025-01-06 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankapp', '0009_alter_transaction_details_account_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_details',
            name='account_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Bankapp.bankloging'),
            preserve_default=False,
        ),
    ]
